server:
  port: 8080

chaos:
  fail-on-missing-scenario: true
  control:
    enabled: true
  scenarios:
    orders-create:
      enabled: true
      delay:
        probability: 0.20
        max-ms: 250
      exception:
        probability: 0.02

    orders-read:
      enabled: true
      delay:
        probability: 0.10
        max-ms: 150
      exception:
        probability: 0.01

    orders-payment:
      enabled: true
      delay:
        probability: 0.60
        max-ms: 1200
      exception:
        probability: 0.20
